@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

/' les classes de test ne sont pas représentées sur l'uml'/
package bataille_navale{


    package view{
        class GameSettings{}

        class ObjectsPlacement{}

        class AfficherGrille implements bataille_navale.models.GridObserver

        class GameEnd{}
    }

    package controller{

            package gameController{
                class GameController{
                    + <<create>> GameController(view : AfficherGrille, humanPlayer : HumanPlayer, computerPlayer : Computer)
                    + handleCellClick(player : Player, x : Integer, y : Integer)
                }

                enum ActionType{
                    BASIC_ATTACK
                    BOMB
                    SONAR
                }
            }

            package players{
                abstract class Player{ /' C'EST UNE CLASSE ABSTRAITE, CAR ON VA IMPLEMENTER LES METHODES DE LA MEME MANIERE '/
                    - type : PlayerType
                    - usableItems : ArrayList<Item>
                    - playerGrid : Grid
                    - enemyGrid : Grid
                    + getGrid() : Grid
                    + getEnemyGrid(): Grid
                    + getType(): PlayerType
                    + getUsableItems(): ArrayList<Item>
                    + placeBoats()
                    + playerTurn()
                    + addItem(item : Item)
                    + usableItemsContainsSonar() : boolean
                    + usableItemsContainsBomb() : boolean
                    + setGrid(playerGrid : Grid, enemyGrid : Grid)
                }

                class HumanPlayer extends Player{
                    + getEnemyGrid() : Grid
                    + basicAttack(player : Player, x : Integer, y : Integer)
                    + useBomb(x : integer, y : integer)
                    + useSonar(x : Integer, y : Integer) :Integer
                    + playerTurn()
                    + addBoatToPlace(boat : Boat)
                    + isGridEmpty() : boolean
                }

                class Computer extends Player{
                    + playerTurn(): Integer[]
                    + basicAttack() : Integer[]
                    + optimizedAttack() : Integer[]
                }
            }

    }
    package models{

        /'class Coordinates{
            - x : Integer
            - y : Integer
            + <<create>> Coordinates(x : Integer, y : Integer)
            - notifyTrapObservers()
            + getX(): Integer
            + getY(): Integer
        }'/
        package Objects{

            abstract class Object <<abstract>>{
                - x : Integer
                - y : Integer
                -size: Integer
                + <<create>> Object(size : Integer)
                + getSize() : Integer
                + onHit(grid : Grid, x : Integer, y : Integer)
            }

            package boat{

                class Boat extends bataille_navale.models.Objects.Object {
                  - hits : Integer
                  - type : Types
                  - boatDirection : BoatDirection
                  - coordinates : ArrayList<BoatCoordinates>
                  + <<create>> Boat(type : BoatType, direction : BoatDirection, size : Integer)

                  + getBoatSize() : Integer
                  + isSunk() : boolean
                  + increaseHits()
                  + onHit(player : Player, x : Integer, y : Integer)
                  + getHits() : Integer
                  + getBoatDirection() : BoatDirection
                  + getBoatCoordinates(): ArrayList<BoatCoordinates>
                  + setBoatCoordinates(x : Integer, y : Integer)
                }

                class BoatCoordinates{
                    - x : Integer
                    - y : Integer
                    + <<create>> BoatCoordinates(x : Integer, y : Integer)
                    + getX() : Integer
                    + getY() : Integer
                }

                enum BoatType <<enumerate>> {
                    PORTE_AVION
                    CROISEUR
                    CONTRE_TORPILLEUR
                    SOUS_MARIN
                    TORPILLEUR
                }

                enum BoatDirection <<enumerate>> {
                    HORIZONTAL
                    VERTICAL
                }

                class BoatFactory{
                  + createPorteAvion(direction : BoatDirection) : Boat
                  + createCroiseur(direction : BoatDirection) : Boat
                  + createContreTorpilleur(direction : BoatDirection) : Boat
                  + createSousMarin(direction : BoatDirection) : Boat
                  + createTorpilleur(direction : BoatDirection) : Boat

                }
            }

            package island{
                class Island extends bataille_navale.models.Objects.Object{
                    - item : Item

                    + <<create>> Island(size : Integer, item : Item)
                    + <<create>> Island(size : Integer)
                    + onHit(player : Player, x : Integer, y : Integer)
                }
            }


            package items{

                abstract class Item <<abstract>> extends bataille_navale.models.Objects.Object{
                    + <<create>> Item(capacity : Integer, objectType : ObjectType)
                    - capacity : Integer
                    + canBeUsed() : boolean
                    + addCapacity()
                }

                package weapons{
                    abstract class Weapon <<abstract>> extends bataille_navale.models.Objects.items.Item{
                        + <<create>> Weapon(size : Integer, capacity : Integer)
                        + useWeapon(player : Player, x : Integer, y : Integer)
                        + onHit(player : Player, x : Integer, y : Integer)
                    }

                    class Bomb extends Weapon{
                        + <<create>> Bomb(capacity : Integer, objectType : ObjectType)
                        + getCanBeThrown() : Boolean
                        + useWeapon (x : Integer, y : Integer, player : Player)
                    }

                    class Sonar extends Weapon{
                        - submarineIsAlive : boolean
                        - canBeUsed : boolean
                        + <<create>> sonar(capacity : Integer, objectType : ObjectType)
                        + useSonar (x : Integer, y : Integer, g : Grid)
                        + getSubmarineIsAlive() : boolean
                        + setSubmarineIsAlive( submarineIsAlive : boolean)
                        + getCanBeUsed() : Boolean
                        + setCanBeUsed( canBeUsed : boolean)

                    }
                }

                package traps {

                    abstract class Trap <<abstract>> extends bataille_navale.models.Objects.items.Item{
                        + <<create>> Trap(capacity : Integer)
                    }

                    class BlackHole extends Trap{
                        + <<create>> BlackHole(size : Integer)
                        + getCanBePlaced() : boolean
                        + setCanBePlaced( setCanBePlaced : boolean)
                        + onHit(player : Player, x : Integer, y : Integer)

                    }

                    class Tornado extends Trap{
                        + <<create>> Tornado(size : Integer)
                        + getCanBePlaced() : boolean
                        + setCanBePlaced( setCanBePlaced : boolean)
                        + onHit(player : Player, x : Integer, y : Integer)
                    }

                }
            }
        }

        package map{

            class Grid{
                - height : Integer
                - width : Integer
                + <<create>> Grid()
                + <<create>> Grid(hauteur : Integer, longueur : Integer )
                + getGrille() : Object[][]
                + getCase() : Object
                + getHeight() : Integer
                + getWidth(): Integer
                + getNbBoats() : Integer
                + setIsland()
                + setBoat(x : Integer, y : Integer, Boat boat) : boolean
                + setTrap(x : Integer, y : Integer, trap : Trap) : boolean
                + removeBoat(boat : Boat)
                + basicAttack(player : Player, x : Integer, y : Integer)
                + sonarAttack(sonar : Sonar, player : Player, x : Integer, y : Integer)
                + bombAttack(bomb : Bomb, player : Player, x : Integer, y : Integer)
                + cellExists(x : Integer, y : Integer) : boolean
                + setBoats1(g : Grid)
                + allBoatsSunk() : boolean
                + addNbBoatsSunk()
                + addObserver(observer : GridObserver)
                + removeObserver(observer : GridObserver)
                + notifyObserversGrid()
                + notifyObserversCell(x : Integer, y : Integer)
            }

            class BateauCoule extends bataille_navale.models.Objects.Object{
                + <<create>> BateauCoule(size : Integer, objectType : ObjectType)
                + onHit(player : Player, x : Integer, y : Integer)
            }

            class CaseAttaquee extends bataille_navale.models.Objects.Object{
                + <<create>> BateauCoule(size : Integer, objectType : ObjectType)
                + onHit(player : Player, x : Integer, y : Integer)
            }

            class IleTouchee extends bataille_navale.models.Objects.Object{
                + <<create>> BateauCoule(size : Integer, objectType : ObjectType)
                + onHit(player : Player, x : Integer, y : Integer)
            }

            class TrapHit extends bataille_navale.models.Objects.Object{
                + <<create>> BateauCoule(size : Integer, objectType : ObjectType)
                + onHit(player : Player, x : Integer, y : Integer)
            }

            class Water extends bataille_navale.models.Objects.Object{
                + <<create>> BateauCoule(size : Integer, objectType : ObjectType)
                + onHit(player : Player, x : Integer, y : Integer)
            }
        }

        enum ObjectType{
            BOAT
            SUNK_BOAT
            HIT_BOAT
            TRAP
            WEAPON
            SONAR
            WATER
            ISLAND
            HIT_ISLAND
        }

        class TurnLogs{
            + <<create>> TurnLogs()
            + showPlayerAttack(actionType: ActionType, x : Integer, y : Integer)
            + showComputerAttack(actionType: ActionType, x : Integer, y : Integer)
        }




        interface GridObserver{
            + update(grid : Grid)
        }

        class Game{
            + creerPartie()
            + jouerPartie()
            + detecterFin()
            + recommencerPartie()
            + modeIle(): boolean
        }

    }
}

class Main{
}

Main .> Game : <<uses>>
Bomb .> Grid : <<uses>>





/'relations de Grid '/
bataille_navale.models.map.Grid ..> Player : <<uses>>
bataille_navale.models.map.Grid ..> Sonar : <<uses>>
bataille_navale.models.map.Grid ..> Bomb : <<uses>>
bataille_navale.models.map.Grid ..> GridObserver : <<uses>>
bataille_navale.models.map.Grid ..> Boat : <<uses>>

bataille_navale.models.map.Grid *-- GridObserver
Grid "1..*" *--> "1..*\n-listObject" bataille_navale.models.Objects.Object: contient \n >
bataille_navale.models.map.Grid *-- Island : instancie

/' relations cases touchées '/
bataille_navale.models.map.BateauCoule *-- ObjectType : possède
bataille_navale.models.map.CaseAttaquee *-- ObjectType : possède
bataille_navale.models.map.IleTouchee *-- ObjectType : possède
bataille_navale.models.map.TrapHit *-- ObjectType : possède
bataille_navale.models.map.Water *-- ObjectType : possède



bataille_navale.models.map.BateauCoule ..> Player : <<uses>>
bataille_navale.models.map.CaseAttaquee ..> Player : <<uses>>
bataille_navale.models.map.IleTouchee ..> Player : <<uses>>
bataille_navale.models.map.TrapHit ..> Player : <<uses>>
bataille_navale.models.map.Water ..> Player : <<uses>>


/' relations Boat '/
Boat "1" *--> "1\n-typeBateau" BoatType: est \n >
Boat "1" *--> "1\n-orientation" BoatDirection: s'oriente \n >
Boat "1" *--> BoatCoordinates: possède \n >

Boat ..> BoatDirection : <<uses>>
Boat ..> BoatType : <<uses>>
Boat ..> Player : <<uses>>

/' relations BoatCoordinates '/

/' relations BoatFactory '/
BoatFactory ..> Boat : <<uses>>
BoatFactory ..> BoatDirection : <<uses>>

/' relations Island '/
Island ..> Player : <<uses>>
Island *-- Item : possède

/' relations BlackHole '/
BlackHole ..> Player : <<uses>>
BlackHole ..> bataille_navale.models.map.Grid : <<uses>>

/' relations Tornado '/
Tornado ..> Player : <<uses>>

/' relations Trap '/

/' relations Bomb '/
Trap ..> Player : <<uses>>
Trap ..> ObjectType : <<uses>>

/' relations Sonar '/
Sonar ..> bataille_navale.models.map.Grid : <<uses>>
Sonar ..> ObjectType : <<uses>>

/' relations Weapon '/
Weapon ..> ObjectType : <<uses>>

/' relations Item '/
Item ..> ObjectType : <<uses>>

/' relations Game '/
Game ..> ActionType : <<uses>>
Game ..> Player : <<uses>>

Game o-- HumanPlayer : possède
Game o-- Computer : possède

/' relations Object '/
Object o-- ObjectType : possède
Object ..> Player : <<uses>>

/' relations TurnLogs '/
TurnLogs ..> ActionType : <<uses>>

/' relations AfficherGrille '/
AfficherGrille o-- bataille_navale.models.map.Grid : possède
AfficherGrille ..> Grid : <<uses>>
AfficherGrille ..> ObjectType : <<uses>>


/' relations GameEnd '/
GameEnd ..> HumanPlayer : <<uses>>
GameEnd ..> Computer : <<uses>>

GameEnd *-- Grid : crée

/' relations GameSettings '/

GameSettings ..> HumanPlayer : <<uses>>
GameSettings ..> Computer : <<uses>>
GameSettings ..> bataille_navale.models.map.Grid : <<uses>>
GameSettings ..> BoatFactory : <<uses>>
GameSettings ..> BoatDirection : <<uses>>

/' relations ObjectsPlacement '/
ObjectsPlacement o-- bataille_navale.models.map.Grid : possède
ObjectsPlacement o-- HumanPlayer : possède
ObjectsPlacement o-- Computer : possède
ObjectsPlacement ..> GameController : <<uses>>
ObjectsPlacement ..> BlackHole : <<uses>>

/' relations GameController '/

GameController o-- HumanPlayer : possède
GameController o-- Computer : possède
GameController o-- Game : possède
GameController o-- TurnLogs : possède
GameController o-- Player : possède
GameController o-- ActionType : possède
GameController o-- AfficherGrille : possède











@enduml