@startuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

/' REFLECHIR A IMPLEMENTER OBSERVER POUR LAFFICHAGE DES TOURS DANS LE TERMINAL '/
package bataille_navale{


    package view{
        class EcranDeConfiguration{}

        class EcranDePlacement{}

        class EcranPrincipal{}

        class EcranDeFin{}
    }

    package controller{

            package players{
                abstract class Player{ /' C'EST UNE CLASSE ABSTRAITE, CAR ON VA IMPLEMENTER LES METHODES DE LA MEME MANIERE '/
                    + placerBateauxFixe()
                    + placerBateauxAleatoire()
                }

                class HumanController extends Player{
                    + tir()
                    + placerTornade(x : integer, y : integer)
                    + placerTrouNoir(x : integer, y : integer)
                }

                class ComputerController extends Player{
                    + tirAleatoire()
                    + placerTornade() : boolean
                    + placerTrouNoir() : boolean
                }
            }

    }
    package models{

        class Coordinates{
            - x : Integer
            - y : Integer
            + <<create>> Coordinates(x : Integer, y : Integer)
            - notifyTrapObservers()
            + getX(): Integer
            + getY(): Integer
        }

        package boat{

            class Boat extends bataille_navale.models.Object {
              + <<create>> Boat(type : BoatType, direction : BoatDirection, size : Integer)
              + isSunk() : boolean
            }

            enum BoatType <<enumerate>> {
                PORTE_AVION
                CROISEUR
                CONTRE_TORPILLEUR
                SOUS_MARIN
                TORPILLEUR
            }

            enum BoatDirection <<enumerate>> {
                HORIZONTAL
                VERTICAL
            }
        }

        package map{

            class Map{
                - height : Integer
                - width : Integer
                - nbObject : Integer
                + <<create>> Map()
                + <<create>> Map(hauteur : Integer, longueur : Integer )
            }
        }

        abstract class Object <<abstract>>{
            #size: Integer
            +getSize() : Integer
            + <<create>> Object(size : Integer)
            + <<create>> Object(size : Integer, listCoordiantes : Coordinates [*])
        }

        package items{

            abstract class Item <<abstract>> extends bataille_navale.models.Object{
                + <<create>> Item()
                - capacity : Integer
                + canBeUsed() : boolean
                + addCapacity()
            }

            package weapons{
                abstract class Weapon <<abstract>> extends bataille_navale.models.items.Item{
                    + {abstract} useWeapon (target: Coordinates)
                }

                class Bomb extends Weapon{
                    + <<create>> bombe()
                    + useWeapon (target: Coordinates)
                }

                class Sonar extends Weapon{
                    + <<create>> sonar(size : Integer)
                    + useWeapon (target: Coordinates)
                    - submarineIsAlive() : boolean
                    + getSubmarineIsAlive() : boolean
                    + setSubmarineIsAlive( submarineIsAlive : boolean)

                }
            }

            package traps {

                abstract class Trap <<abstract>> extends bataille_navale.models.items.Item{
                    + {abstract} trapEffect()
                }

                class BlackHole extends Trap{
                    + <<create>> BlackHole(size : Integer)
                    + trapEffect()

                }

                class Tornado extends Trap{
                    + <<create>> Tornado(size : Integer)
                    + trapEffect()
                }

            }
        }


        class Game{
            + creerPartie()
            + jouerPartie()
            + detecterFin()
            + recommencerPartie()
            + modeIle(): boolean
        }

    }
}

class Main{
}

Main .> Game : <<uses>>

Boat "1" *--> "1\n-typeBateau" BoatType: est \n >
Boat "1" *--> "1\n-orientation" BoatDirection: s'oriente \n >
Object "1..*" *--> "1..*\n #listCoordinates" Coordinates: est placé selon \n >


Map "1..*" *--> "1..*\n-listObject" Object: contient \n >

@enduml